---
- name: Task-5.3
  hosts: all
  become: yes
  vars_files:
    - vars/main.yml  # Подключаем зашифрованный файл с токеном
  roles:
    - role: nodejs
    - role: clone_repo
      install_site: true

