---
#- name: Converge
#  hosts: all
#  roles:
#  - role: nodejs
- name: Converge
  hosts: windows
  gather_facts: false
  tasks:
    - name: Include Windows tasks
      include_role:
        name: nodejs
      vars:
        ansible_connection: winrm
        ansible_winrm_server_cert_validation: ignore
