---
- name: Update packages npm with package.json
  npm:
    path: "{{ gitlab_clone_dest }}/{{ folder_name }}"
    state: latest

- name: Start website with PM2
  shell: |
    cd {{ gitlab_clone_dest }}/{{ folder_name }}
    node index.js
  async: 100
  poll: 0
  notify: "Check site status"
