---
# tasks file for clone_repo
- name: clone
  ansible.builtin.git:
    repo: "https://{{ gitlab_username }}:{{ gitlab_token }}@{{ gitlab_repo_url | regex_replace('https://', '') }}"
    dest: "{{ gitlab_clone_dest }}/{{ folder_name }}"
    version: "{{ gitlab_version }}"
  when: gitlab_clone_enabled | bool
  no_log: true  # Скрыть токен в логах
  tags: clone

- name: Include install_site
  include_tasks: install_site.yml
  when: gitlab_clone_enabled
